# Generated by Django 4.1 on 2022-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_author',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
